### ISSUE TITLE
TODO / Suggestion List

### ISSUE THREAD

**Issue by TacoTheDank** [RodrigoDavy/PixelArtist#28]
- [ ] Undo & redo function
- [ ] Add capability to resize canvas
- [ ] Add capability to zoom in/out using two finger pinch/spread gesture or a zoom button
- [ ] Remodel the sidebar UI (to use material I guess)
- [ ] Support for multiple color rows
- [ ] Possibly have the top bar change to the color that is selected
- [ ] Possibly a dark UI theme?

More will be added as I think of them.

**Comment by RodrigoDavy** [comment]
>Save function FIRST & FOREMOST (how a pixel art app could be allowed to exist without a save function is beyond me lol)

Could you be more specific about the Save function? Like, what you expect to do and how it should work.

The app does have a (very crappy) Save function. The way it works is that it uses a format that only Pixel Artist can read and it saves it with the internal app's data. Once you save, the saved files should appear when you use the Open function. I guess it's neither very user friendly nor what an user would expect from a save function, so I totally agree that there's a lot to improve

Funilly enough, I was thinking about how it doesn't have a Remove option.

>Possibly have the top bar change to the color that is selected

I'm guessing your mean the App Bar. This is actually how it used to behave in early versions of the app when I was figuring out how to signal the selected color. You can find screenshots displaying these behaviours in the Telegram channel I included in the Readme file, where I post some of my "art"

There's a problem that is difficult to solve with this approach though, changing the color of the App Bar made the action icons for the Actions in the App Bar hard to see depending on the current color, due to lack of contrast

**Comment by TacoTheDank** [comment]
The save function ideally should just open a save prompt in the phone's local file manager, and you choose a location for the app to save the file (including support for an external sd card if someone chooses it). It's perfectly ok for the app to use a file only it can read. It's just saving the data for later when you open it back up. Saving it as something else is what the export function would be for.

About the app bar, if you look at SimpleMobileTools's apps ([this one](https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/), for example), go into the settings and change the app theme. The dev has amazingly coded it to where if the theme is set dark enough, the text automatically turns white. I imagine the app bar could function like this. We could look at the code and see what he did.
